import gradio as gr
import logging
import os
from typing import List, Tuple
from src.recommender import BookRecommender
from src.utils import setup_logger

# --- Initialize Logger ---
logger = setup_logger(__name__)

# --- Module Initialization (Lazy Loading to prevent crash) ---
recommender = None
shopping_agent = None

try:
    logger.info("Initializing BookRecommender...")
    recommender = BookRecommender()
    categories = recommender.get_categories()
    tones = recommender.get_tones()
except Exception as e:
    logger.error(f"Failed to initialize recommender: {e}")
    recommender = None
    categories = ["All"]
    tones = ["All"]

# Initialize Shopping Agent (Mock or Real)
# Note: Real agent requires FAISS index. We'll handle checks later.
try:
    # from src.agent.agent_core import ShoppingAgent
    # shopping_agent = ShoppingAgent(...)
    pass 
except ImportError:
    logger.warning("Shopping Agent module not found or failed to import.")

# --- Business Logic: Tab 1 (Discovery) ---
def recommend_books(query: str, category: str, tone: str) -> List[Tuple[str, str]]:
    try:
        if not query.strip(): return []
        if not recommender: return []
        
        results = recommender.get_recommendations(query, category, tone)
        return [(item["thumbnail"], f"{item['title']}\n{item['authors']}") for item in results]
    except Exception as e:
        logger.error(f"Error in recommend_books: {e}")
        return []

def clear_discovery():
    return "", "All", "All", []

# --- Business Logic: Tab 2 (Assistant) ---
def chat_response(message, history):
    # Placeholder for Agent integration
    # if shopping_agent: return shopping_agent.process_query(message)
    try:
        # Mock Response for Demo
        if "cheap" in message.lower():
            return "I found some budget-friendly options for you. Check out 'The Great Gatsby' (Public Domain) or used copies of '1984'."
        return f"I understand you are looking for '{message}'. Based on our RAG engine, I recommend checking the Discovery tab for detailed matches."
    except Exception as e:
        return f"Error: {str(e)}"

# --- Business Logic: Tab 3 (Marketing) ---
def generate_marketing_copy(product_name, features, target_audience):
    # Placeholder for Marketing Content Engine
    # from src.marketing.guardrails import SafetyCheck...
    return f"""
    📣 **ATTENTION {target_audience.upper()}!**
    
    Meet the new **{product_name}** - the game changer you've been waiting for.
    
    ✨ **Why you'll love it:**
    {features}
    
    [Generated by Safe-Aligned-LLM v1.0]
    [Safety Check: PASSED]
    """

# --- UI Construction ---
with gr.Blocks(title="AI E-Commerce Platform", theme=gr.themes.Soft()) as dashboard:
    
    gr.Markdown("# 🚀 End-to-End AI E-Commerce Platform")
    gr.Markdown("Demonstrating 3 Core AI Modules: **Neural Search**, **RAG Agent**, and **Generative Marketing**.")
    
    with gr.Tabs():
        
        # --- Tab 1: Discovery ---
        with gr.TabItem("🔍 Smart Discovery (RecSys)"):
            with gr.Row():
                with gr.Column(scale=3):
                    q_input = gr.Textbox(label="Describe what you want (Semantic Search)", placeholder="e.g., A sci-fi novel about space exploration...")
                with gr.Column(scale=1):
                    cat_input = gr.Dropdown(label="Category", choices=categories, value="All")
                    tone_input = gr.Dropdown(label="Tone/Emotion", choices=tones, value="All")
            
            btn_rec = gr.Button("Find Books", variant="primary")
            gallery = gr.Gallery(label="Recommendations", columns=4, height="auto")
            
            btn_rec.click(recommend_books, [q_input, cat_input, tone_input], gallery)

        # --- Tab 2: AI Assistant ---
        with gr.TabItem("💬 Shopping Assistant (RAG)"):
            chatbot = gr.ChatInterface(
                fn=chat_response,
                examples=["Recommend a book for learning Python", "I want a sad love story"],
                title="Intelligent Shopping assistant",
                description="Powered by RAG (Retrieval Augmented Generation) & Intent Parsing."
            )

        # --- Tab 3: Marketing ---
        with gr.TabItem("✍️ Marketing Generator (GenAI)"):
            with gr.Row():
                m_name = gr.Textbox(label="Product Name", value="Quantum Reader X1")
                m_feat = gr.Textbox(label="Key Features", value="E-ink display, Waterproof, 1-year battery")
                m_aud = gr.Textbox(label="Target Audience", value="Book Lovers")
            
            btn_gen = gr.Button("Generate Copy", variant="primary")
            m_out = gr.Markdown(label="Generated Copy")
            
            btn_gen.click(generate_marketing_copy, [m_name, m_feat, m_aud], m_out)

if __name__ == "__main__":
    dashboard.launch(server_name="0.0.0.0", server_port=7860)