import gradio as gr
import logging
import os
import requests
import json
from typing import List, Tuple, Any
from src.utils import setup_logger

# --- Configuration ---
API_URL = os.getenv("API_URL", "http://localhost:6006")  # Localhost via SSH Tunnel

# --- Initialize Logger ---
logger = setup_logger(__name__)

# --- Module Initialization ---
# (We no longer load model locally; we query the remote API)
categories = ["All", "Fiction", "History", "Science", "Technology"] # Fallback/Mock for now
tones = ["All", "Happy", "Surprising", "Angry", "Suspenseful", "Sad"]

def fetch_categories():
    try:
        resp = requests.get(f"{API_URL}/categories", timeout=2)
        if resp.status_code == 200:
            return ["All"] + resp.json()
    except:
        pass
    return categories

# Try to fetch real categories on startup
categories = fetch_categories()

# Initialize Shopping Agent (Mock or Real)
# Note: Real agent requires FAISS index. We'll handle checks later.
try:
    # from src.agent.agent_core import ShoppingAgent
    # shopping_agent = ShoppingAgent(...)
    pass 
except ImportError:
    logger.warning("Shopping Agent module not found or failed to import.")

# --- Business Logic: Tab 1 (Discovery) ---
def recommend_books(query: str, category: str, tone: str):
    """Fetch recommendations and return both gallery items and raw data."""
    try:
        if not query.strip():
            return [], []
        
        payload = {
            "query": query,
            "category": category if category else "All",
            "tone": tone if tone else "All"
        }
        
        logger.info(f"Sending request to {API_URL}/recommend")
        response = requests.post(f"{API_URL}/recommend", json=payload, timeout=10)
        
        if response.status_code == 200:
            data = response.json()
            results = data.get("recommendations", [])
            gallery_items = [(item["thumbnail"], f"{item['title']}\n{item['authors']}") for item in results]
            return gallery_items, results
        else:
            logger.error(f"API Error: {response.text}")
            return [], []
            
    except Exception as e:
        logger.error(f"Error in recommend_books: {e}")
        return [], []


def show_book_details(evt: Any, recs: List[dict]):
    """Populate detail panel when a gallery item is selected."""
    try:
        if recs is None:
            return "", "", "", ""
        idx = evt.index if evt and hasattr(evt, "index") else None
        if idx is None or idx >= len(recs):
            return "", "", "", ""
        book = recs[idx]
        title_block = f"### {book['title']}\n**Authors:** {book['authors']}\n**ISBN:** {book['isbn']}"
        desc_block = f"**Description**\n\n{book['description']}"
        rank_block = f"**Rank:** #{idx + 1}"  # simple positional rank
        comments_block = "**Comments (sample):**\n- Loved the pacing and tone.\n- Great pick for this category."
        return title_block, rank_block, comments_block, desc_block
    except Exception as e:
        logger.error(f"Error showing book details: {e}")
        return "", "", "", ""

def clear_discovery():
    return "", "All", "All", []

# --- Business Logic: Tab 2 (Assistant) ---
def chat_response(message, history):
    # Placeholder for Agent integration
    # if shopping_agent: return shopping_agent.process_query(message)
    try:
        # Mock Response for Demo
        if "cheap" in message.lower():
            return "I found some budget-friendly options for you. Check out 'The Great Gatsby' (Public Domain) or used copies of '1984'."
        return f"I understand you are looking for '{message}'. Based on our RAG engine, I recommend checking the Discovery tab for detailed matches."
    except Exception as e:
        return f"Error: {str(e)}"

# --- Business Logic: Tab 3 (Marketing) ---
def generate_marketing_copy(product_name, features, target_audience):
    # Placeholder for Marketing Content Engine
    # from src.marketing.guardrails import SafetyCheck...
    return f"""
    📣 **ATTENTION {target_audience.upper()}!**
    
    Meet the new **{product_name}** - the game changer you've been waiting for.
    
    ✨ **Why you'll love it:**
    {features}
    
    [Generated by Safe-Aligned-LLM v1.0]
    [Safety Check: PASSED]
    """

# --- UI Construction ---
with gr.Blocks(title="AI E-Commerce Platform", theme=gr.themes.Soft()) as dashboard:
    
    gr.Markdown("# 🚀 End-to-End AI E-Commerce Platform")
    gr.Markdown("Demonstrating 3 Core AI Modules: **Neural Search**, **RAG Agent**, and **Generative Marketing**.")
    
    with gr.Tabs():
        
        # --- Tab 1: Discovery ---
        with gr.TabItem("🔍 Smart Discovery (RecSys)"):
            rec_state = gr.State([])  # store full recommendation data
            with gr.Row():
                with gr.Column(scale=3):
                    q_input = gr.Textbox(label="Describe what you want (Semantic Search)", placeholder="e.g., A sci-fi novel about space exploration...")
                with gr.Column(scale=1):
                    cat_input = gr.Dropdown(label="Category", choices=categories, value="All")
                    tone_input = gr.Dropdown(label="Tone/Emotion", choices=tones, value="All")
            
            btn_rec = gr.Button("Find Books", variant="primary")
            gallery = gr.Gallery(label="Recommendations", columns=4, height="auto")
            with gr.Row():
                with gr.Column(scale=2):
                    title_info = gr.Markdown(label="Book")
                    desc_info = gr.Markdown(label="Description")
                with gr.Column(scale=1):
                    rank_info = gr.Markdown(label="Rank")
                    comments_info = gr.Markdown(label="Comments")

            btn_rec.click(recommend_books, [q_input, cat_input, tone_input], [gallery, rec_state])
            gallery.select(show_book_details, [rec_state], [title_info, rank_info, comments_info, desc_info])

        # --- Tab 2: AI Assistant ---
        with gr.TabItem("💬 Shopping Assistant (RAG)"):
            chatbot = gr.ChatInterface(
                fn=chat_response,
                examples=["Recommend a book for learning Python", "I want a sad love story"],
                title="Intelligent Shopping assistant",
                description="Powered by RAG (Retrieval Augmented Generation) & Intent Parsing."
            )

        # --- Tab 3: Marketing ---
        with gr.TabItem("✍️ Marketing Generator (GenAI)"):
            with gr.Row():
                m_name = gr.Textbox(label="Product Name", value="Quantum Reader X1")
                m_feat = gr.Textbox(label="Key Features", value="E-ink display, Waterproof, 1-year battery")
                m_aud = gr.Textbox(label="Target Audience", value="Book Lovers")
            
            btn_gen = gr.Button("Generate Copy", variant="primary")
            m_out = gr.Markdown(label="Generated Copy")
            
            btn_gen.click(generate_marketing_copy, [m_name, m_feat, m_aud], m_out)

if __name__ == "__main__":
    import os
    assets_path = os.path.join(os.path.dirname(__file__), "assets")
    dashboard.launch(
        server_name="0.0.0.0", 
        server_port=7860,
        allowed_paths=[assets_path]
    )