#!/usr/bin/expect

set host "connect.nmb2.seetacloud.com"
set port "15054"
set user "root"
set password "9Dml+WZeqp5b"
set remote_dir "/root/autodl-tmp/book-rec-with-LLMs"

spawn ssh -p $port $user@$host "ls -F $remote_dir/src/services/"

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "continue connecting" {
        send "yes\r"
        exp_continue
    }
    eof
}
