#!/usr/bin/expect

set host "connect.nmb2.seetacloud.com"
set port "15054"
set user "root"
set password "9Dml+WZeqp5b"
set local_dir "."
set remote_dir "/root/autodl-tmp/book-rec-with-LLMs"

# Create local dir just in case
# mkdir -p data/model/rec ?

# Fetch user embeddings
spawn scp -P $port $user@$host:$remote_dir/data/rec/user_seq_emb.pkl $local_dir/data/rec/
set timeout -1
expect {
    "password:" { send "$password\r" }
}
expect eof

# Fetch model (to get item embeddings)
# Note on server it saves to ../model/rec/sasrec_model.pth relative to data/rec
# So it is at /root/autodl-tmp/book-rec-with-LLMs/data/model/rec/sasrec_model.pth
spawn scp -P $port $user@$host:$remote_dir/data/model/rec/sasrec_model.pth $local_dir/data/model/rec/
expect {
    "password:" { send "$password\r" }
}
expect eof

puts "Fetch Complete!"
